CREATE TABLE items (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    brand TEXT,
    price DECIMAL(10,2) NOT NULL,
    serial_number TEXT NOT NULL,
    purchase_date TIMESTAMPTZ NOT NULL,
    purchase_place TEXT 
);